tab_spaces = 2
hard_tabs = true
reorder_imports = true
reorder_impl_items = true
newline_style = "Unix"
#fn_params_layout = "Vertical"
empty_item_single_line = false
use_field_init_shorthand = true
#max_width = 180
overflow_delimited_expr = true
group_imports = "StdExternalCrate"