[package]
name = "tree"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmic-text = "0.12.1"
pretty_env_logger = "0.5.0"
taffy = "0.7.1"
torque = { version = "0.1.0", path = "../../crates/torque" }
