[package]
edition = "2021"
name = "torque-layout"
version = "0.1.0"

[dependencies]
m8 = { version = "0.1.0", path = "../m8" }
torque-ecs = { version = "0.1.0", path = "../torque-ecs" }
torque-style = { version = "0.1.0", path = "../torque-style" }
v8.workspace = true
